"""update_bot_and_strategy_tables_for_enhanced_models

Revision ID: f3595aea39b7
Revises: 9cae27c1dab6
Create Date: 2025-12-16 09:16:05.326680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3595aea39b7'
down_revision: Union[str, Sequence[str], None] = '9cae27c1dab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_connections', 'api_key_encrypted',
               existing_type=sa.TEXT(),
               comment='Encrypted mainnet API key (Fernet)',
               existing_comment='Encrypted API key (Fernet)',
               existing_nullable=False)
    op.alter_column('api_connections', 'secret_key_encrypted',
               existing_type=sa.TEXT(),
               comment='Encrypted mainnet secret key (Fernet)',
               existing_comment='Encrypted secret key (Fernet)',
               existing_nullable=False)
    # Add nullable columns first, then update defaults
    op.add_column('bots', sa.Column('exchange_connection_id', sa.UUID(), nullable=True))
    op.add_column('bots', sa.Column('description', sa.String(length=500), nullable=True, comment='Bot description'))
    op.add_column('bots', sa.Column('risk_level', sa.String(length=20), nullable=True, comment='Risk level'))
    op.add_column('bots', sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Bot configuration JSON'))
    op.add_column('bots', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='Bot start timestamp'))
    op.add_column('bots', sa.Column('stop_time', sa.DateTime(timezone=True), nullable=True, comment='Bot stop timestamp'))
    op.add_column('bots', sa.Column('last_error', sa.String(length=1000), nullable=True, comment='Last error message'))
    op.add_column('bots', sa.Column('performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Performance metrics JSON'))
    op.add_column('bots', sa.Column('active_orders', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Active order IDs JSON array'))
    op.add_column('bots', sa.Column('daily_pnl', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Daily P&L'))
    op.add_column('bots', sa.Column('total_runtime_seconds', sa.Integer(), nullable=True, comment='Total runtime in seconds'))
    op.add_column('bots', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata JSON'))
    
    # Copy data from old columns before dropping
    op.execute("UPDATE bots SET configuration = COALESCE(config, '{}'::jsonb)")
    op.execute("UPDATE bots SET performance = COALESCE(performance_stats, '{}'::jsonb)")
    op.execute("UPDATE bots SET last_error = error_message")
    
    # Set defaults for new NOT NULL columns
    op.execute("UPDATE bots SET risk_level = 'MODERATE' WHERE risk_level IS NULL")
    op.execute("UPDATE bots SET active_orders = '[]'::jsonb WHERE active_orders IS NULL")
    op.execute("UPDATE bots SET daily_pnl = 0 WHERE daily_pnl IS NULL")
    op.execute("UPDATE bots SET total_runtime_seconds = 0 WHERE total_runtime_seconds IS NULL")
    op.execute("UPDATE bots SET meta_data = '{}'::jsonb WHERE meta_data IS NULL")
    op.drop_index(op.f('idx_bots_last_run_at'), table_name='bots')
    op.create_index('idx_bots_api_connection_id', 'bots', ['exchange_connection_id'], unique=False)
    op.create_index('idx_bots_start_time', 'bots', ['start_time'], unique=False)
    op.create_foreign_key(None, 'bots', 'api_connections', ['exchange_connection_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('bots', 'performance_stats')
    op.drop_column('bots', 'config')
    op.drop_column('bots', 'last_run_at')
    op.drop_column('bots', 'error_message')
    # Add strategy columns as nullable first
    op.add_column('strategies', sa.Column('strategy_type', sa.String(length=20), nullable=True, comment='Strategy type'))
    op.add_column('strategies', sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is strategy active'))
    op.add_column('strategies', sa.Column('backtest_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Backtest results JSON'))
    op.add_column('strategies', sa.Column('live_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Live performance metrics JSON'))
    
    # Set defaults for strategies
    op.execute("UPDATE strategies SET strategy_type = COALESCE(type, 'CUSTOM') WHERE strategy_type IS NULL")
    op.execute("UPDATE strategies SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE strategies SET live_performance = '{}'::jsonb WHERE live_performance IS NULL")
    op.alter_column('strategies', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               nullable=False,
               existing_comment='Strategy description')
    op.alter_column('strategies', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Strategy parameters JSON',
               existing_comment='Strategy parameters (JSON)',
               existing_nullable=False)
    op.drop_index(op.f('idx_strategies_is_public'), table_name='strategies')
    op.drop_index(op.f('idx_strategies_user_type'), table_name='strategies')
    op.create_index('idx_strategies_user_type', 'strategies', ['user_id', 'strategy_type'], unique=False)
    op.create_index('idx_strategies_is_active', 'strategies', ['is_active'], unique=False)
    op.drop_column('strategies', 'is_public')
    op.drop_column('strategies', 'version')
    op.drop_column('strategies', 'type')
    op.drop_column('strategies', 'backtest_summary')
    
    # Constraint already exists, skip
    # op.create_unique_constraint('uq_symbols_symbol_exchange', 'symbols', ['symbol', 'exchange_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_symbols_symbol_exchange', 'symbols', type_='unique')
    op.add_column('strategies', sa.Column('backtest_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Summary of backtest results'))
    op.add_column('strategies', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Strategy type'))
    op.add_column('strategies', sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Semantic version'))
    op.add_column('strategies', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Public in marketplace?'))
    op.drop_index('idx_strategies_is_active', table_name='strategies')
    op.drop_index('idx_strategies_user_type', table_name='strategies')
    op.create_index(op.f('idx_strategies_user_type'), 'strategies', ['user_id', 'type'], unique=False)
    op.create_index(op.f('idx_strategies_is_public'), 'strategies', ['is_public'], unique=False)
    op.alter_column('strategies', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Strategy parameters (JSON)',
               existing_comment='Strategy parameters JSON',
               existing_nullable=False)
    op.alter_column('strategies', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               nullable=True,
               existing_comment='Strategy description')
    op.drop_column('strategies', 'live_performance')
    op.drop_column('strategies', 'backtest_results')
    op.drop_column('strategies', 'is_active')
    op.drop_column('strategies', 'strategy_type')
    op.add_column('bots', sa.Column('error_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Last error message (if status=ERROR)'))
    op.add_column('bots', sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Last execution timestamp'))
    op.add_column('bots', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Bot configuration (strategy parameters)'))
    op.add_column('bots', sa.Column('performance_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Performance statistics'))
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.drop_index('idx_bots_start_time', table_name='bots')
    op.drop_index('idx_bots_api_connection_id', table_name='bots')
    op.create_index(op.f('idx_bots_last_run_at'), 'bots', ['last_run_at'], unique=False)
    op.drop_column('bots', 'meta_data')
    op.drop_column('bots', 'total_runtime_seconds')
    op.drop_column('bots', 'daily_pnl')
    op.drop_column('bots', 'active_orders')
    op.drop_column('bots', 'performance')
    op.drop_column('bots', 'last_error')
    op.drop_column('bots', 'stop_time')
    op.drop_column('bots', 'start_time')
    op.drop_column('bots', 'configuration')
    op.drop_column('bots', 'risk_level')
    op.drop_column('bots', 'description')
    op.drop_column('bots', 'exchange_connection_id')
    op.alter_column('api_connections', 'secret_key_encrypted',
               existing_type=sa.TEXT(),
               comment='Encrypted secret key (Fernet)',
               existing_comment='Encrypted mainnet secret key (Fernet)',
               existing_nullable=False)
    op.alter_column('api_connections', 'api_key_encrypted',
               existing_type=sa.TEXT(),
               comment='Encrypted API key (Fernet)',
               existing_comment='Encrypted mainnet API key (Fernet)',
               existing_nullable=False)
    # ### end Alembic commands ###
