"""add_market_data_metadata

Revision ID: d31c323aa982
Revises: a1b2c3d4e5f6
Create Date: 2025-12-22 00:22:59.669079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd31c323aa982'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_metadata',
    sa.Column('exchange', sa.String(length=20), nullable=False, comment='Exchange name'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading symbol'),
    sa.Column('timeframe', sa.String(length=5), nullable=False, comment='Candle timeframe'),
    sa.Column('earliest_available_time', sa.DateTime(timezone=True), nullable=True, comment='Earliest data time on exchange'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Data status: EMPTY, PARTIAL, FULL'),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True, comment='Last availability check'),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful fetch'),
    sa.Column('repair_in_progress', sa.Boolean(), nullable=True, comment='Is auto-repair running?'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='Last error message'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', 'timeframe', name='uq_metadata_exchange_symbol_tf'),
    comment='Tracks availability and fetch status of market data periods'
    )
    op.create_index('idx_metadata_status', 'market_data_metadata', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_metadata_status', table_name='market_data_metadata')
    op.drop_table('market_data_metadata')
    # ### end Alembic commands ###
