"""Initial schema with all core tables

Revision ID: c6f60b28d88e
Revises: 
Create Date: 2025-12-15 21:43:44.725808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6f60b28d88e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-increment ID'),
    sa.Column('event_id', sa.UUID(), nullable=False, comment='UUID v7 for deduplication'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Event type'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Event payload (JSON)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Processing status'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Retry attempts'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='Error message if failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Event creation time'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='Processing completion time'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='TTL for cleanup'),
    sa.CheckConstraint("event_type IN ('ORDER_FILLED', 'POSITION_UPDATED', 'ALERT_TRIGGERED', 'BOT_ERROR', 'RISK_VIOLATION')", name='ck_event_queue_type'),
    sa.CheckConstraint("status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')", name='ck_event_queue_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    comment='Event queue for async processing'
    )
    op.create_index('idx_event_queue_event_id', 'event_queue', ['event_id'], unique=True)
    op.create_index('idx_event_queue_expires_at', 'event_queue', ['expires_at'], unique=False)
    op.create_index('idx_event_queue_status_created', 'event_queue', ['status', 'created_at'], unique=False)
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Exchange code (BINANCE, BYBIT, OKX)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Exchange display name'),
    sa.Column('api_base_url', sa.String(length=255), nullable=False, comment='Exchange API base URL'),
    sa.Column('supported_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Supported features (futures, spot, margin)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Exchange active status'),
    sa.Column('rate_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='API rate limits configuration'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code', name='uq_exchanges_code'),
    comment='Supported exchange configurations'
    )
    op.create_index('idx_exchanges_code', 'exchanges', ['code'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email (unique)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt password hash'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='User full name'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='User timezone'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Last login timestamp'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account active status'),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='User preferences (JSON)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    comment='User accounts with authentication'
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_table('alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True, comment='Symbol to monitor (NULL for account-level)'),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Alert type'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Alert name'),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Alert condition (JSON)'),
    sa.Column('message', sa.String(length=500), nullable=True, comment='Custom alert message'),
    sa.Column('notify_email', sa.String(length=20), nullable=False, comment='Send email notification'),
    sa.Column('notify_push', sa.String(length=20), nullable=False, comment='Send push notification'),
    sa.Column('notify_webhook', sa.String(length=500), nullable=True, comment='Webhook URL'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Alert status'),
    sa.Column('trigger_count', sa.Integer(), nullable=False, comment='Number of times triggered'),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True, comment='Last trigger timestamp'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Auto-disable after this time'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.CheckConstraint("status IN ('ACTIVE', 'TRIGGERED', 'DISABLED', 'EXPIRED')", name='ck_alerts_status'),
    sa.CheckConstraint("type IN ('PRICE', 'VOLUME', 'INDICATOR', 'POSITION', 'RISK')", name='ck_alerts_type'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='User-defined alerts and notifications'
    )
    op.create_index('idx_alerts_status_created', 'alerts', ['status', 'created_at'], unique=False)
    op.create_index('idx_alerts_user_symbol_status', 'alerts', ['user_id', 'symbol', 'status'], unique=False)
    op.create_table('api_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Connection name (user-defined)'),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False, comment='Encrypted API key (Fernet)'),
    sa.Column('secret_key_encrypted', sa.Text(), nullable=False, comment='Encrypted secret key (Fernet)'),
    sa.Column('passphrase_encrypted', sa.Text(), nullable=True, comment='Encrypted passphrase (for some exchanges)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Connection active status'),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='API key permissions'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last time credentials were used'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active)'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='User exchange API credentials (encrypted)'
    )
    op.create_index('idx_api_connections_deleted_at', 'api_connections', ['deleted_at'], unique=False)
    op.create_index('idx_api_connections_user_exchange', 'api_connections', ['user_id', 'exchange_id'], unique=False)
    op.create_index(op.f('ix_api_connections_deleted_at'), 'api_connections', ['deleted_at'], unique=False)
    op.create_table('database_configs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Database connection name'),
    sa.Column('db_type', sa.String(length=50), nullable=False, comment='Database type (postgresql, mysql, mongodb, etc.)'),
    sa.Column('host', sa.String(length=255), nullable=False, comment='Database host'),
    sa.Column('port', sa.Integer(), nullable=False, comment='Database port'),
    sa.Column('database_name', sa.String(length=100), nullable=False, comment='Database name'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Database username'),
    sa.Column('password_encrypted', sa.Text(), nullable=False, comment='Encrypted password (Fernet)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Configuration active status'),
    sa.Column('connection_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional connection parameters'),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True, comment='Last connection test timestamp'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='User external database configurations (encrypted)'
    )
    op.create_index('idx_database_configs_deleted_at', 'database_configs', ['deleted_at'], unique=False)
    op.create_index('idx_database_configs_user_id', 'database_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_database_configs_deleted_at'), 'database_configs', ['deleted_at'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-increment ID'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading symbol'),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False, comment='Candle interval'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Candle open time (UTC)'),
    sa.Column('open', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Open price'),
    sa.Column('high', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='High price'),
    sa.Column('low', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Low price'),
    sa.Column('close', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Close price'),
    sa.Column('volume', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Volume in base asset'),
    sa.Column('quote_volume', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Volume in quote asset'),
    sa.Column('num_trades', sa.Integer(), nullable=True, comment='Number of trades'),
    sa.Column('taker_buy_base_volume', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Taker buy volume (base)'),
    sa.Column('taker_buy_quote_volume', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Taker buy volume (quote)'),
    sa.CheckConstraint("interval IN ('1m', '5m', '15m', '1h', '4h', '1d', '1w')", name='ck_market_prices_interval'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='OHLCV market data (partitioned by timestamp)'
    )
    op.create_index('idx_market_prices_symbol_interval_time', 'market_prices', ['symbol', 'exchange_id', 'interval', 'timestamp'], unique=True)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Auto-increment ID'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading symbol'),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Snapshot timestamp (UTC)'),
    sa.Column('bids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Bid orders [[price, quantity], ...]'),
    sa.Column('asks', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Ask orders [[price, quantity], ...]'),
    sa.Column('total_bid_volume', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Total bid volume'),
    sa.Column('total_ask_volume', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Total ask volume'),
    sa.Column('spread', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Best bid-ask spread'),
    sa.Column('mid_price', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Mid price'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Order book depth snapshots (partitioned by timestamp daily)'
    )
    op.create_index('idx_orderbook_symbol_time', 'orderbook_snapshots', ['symbol', 'exchange_id', 'timestamp'], unique=False)
    op.create_table('strategies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Strategy name'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Strategy type'),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Strategy parameters (JSON)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Strategy description'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='Semantic version'),
    sa.Column('backtest_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Summary of backtest results'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Public in marketplace?'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active)'),
    sa.CheckConstraint("type IN ('TECHNICAL', 'ML', 'HYBRID', 'ARBITRAGE', 'GRID', 'DCA')", name='ck_strategies_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Trading strategies (reusable across bots)'
    )
    op.create_index('idx_strategies_deleted_at', 'strategies', ['deleted_at'], unique=False)
    op.create_index('idx_strategies_is_public', 'strategies', ['is_public'], unique=False)
    op.create_index('idx_strategies_user_type', 'strategies', ['user_id', 'type'], unique=False)
    op.create_index(op.f('ix_strategies_deleted_at'), 'strategies', ['deleted_at'], unique=False)
    op.create_table('symbols',
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Symbol code (BTCUSDT)'),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=False, comment='Base asset (BTC)'),
    sa.Column('quote_asset', sa.String(length=20), nullable=False, comment='Quote asset (USDT)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Symbol status (TRADING, HALT, DELISTED)'),
    sa.Column('contract_type', sa.String(length=20), nullable=True, comment='Contract type (PERPETUAL, QUARTERLY, etc.)'),
    sa.Column('price_precision', sa.Integer(), nullable=False, comment='Price decimal precision'),
    sa.Column('quantity_precision', sa.Integer(), nullable=False, comment='Quantity decimal precision'),
    sa.Column('min_order_qty', sa.String(length=50), nullable=True, comment='Minimum order quantity'),
    sa.Column('max_order_qty', sa.String(length=50), nullable=True, comment='Maximum order quantity'),
    sa.Column('min_notional', sa.String(length=50), nullable=True, comment='Minimum order notional value'),
    sa.Column('tick_size', sa.String(length=50), nullable=True, comment='Minimum price increment'),
    sa.Column('step_size', sa.String(length=50), nullable=True, comment='Minimum quantity increment'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('symbol', 'exchange_id'),
    sa.UniqueConstraint('symbol', 'exchange_id', name='uq_symbols_symbol_exchange'),
    comment='Trading symbols/pairs for each exchange'
    )
    op.create_index('idx_symbols_exchange_status', 'symbols', ['exchange_id', 'status'], unique=False)
    op.create_index('idx_symbols_symbol', 'symbols', ['symbol'], unique=False)
    op.create_table('bots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Bot name (user-defined)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Bot status'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Bot configuration (strategy parameters)'),
    sa.Column('performance_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Performance statistics'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='Last execution timestamp'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='Last error message (if status=ERROR)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active)'),
    sa.CheckConstraint("status IN ('RUNNING', 'STOPPED', 'ERROR', 'PAUSED')", name='ck_bots_status'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Trading bots with strategy execution'
    )
    op.create_index('idx_bots_deleted_at', 'bots', ['deleted_at'], unique=False)
    op.create_index('idx_bots_last_run_at', 'bots', ['last_run_at'], unique=False)
    op.create_index('idx_bots_strategy_id', 'bots', ['strategy_id'], unique=False)
    op.create_index('idx_bots_user_status', 'bots', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_bots_deleted_at'), 'bots', ['deleted_at'], unique=False)
    op.create_table('backtests',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=True, comment='Bot used for backtest'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Symbol tested'),
    sa.Column('timeframe', sa.String(length=10), nullable=False, comment='Timeframe'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Backtest start date'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Backtest end date'),
    sa.Column('initial_capital', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Initial capital'),
    sa.Column('final_equity', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Final equity'),
    sa.Column('total_trades', sa.Integer(), nullable=False, comment='Total number of trades'),
    sa.Column('winning_trades', sa.Integer(), nullable=False, comment='Number of winning trades'),
    sa.Column('losing_trades', sa.Integer(), nullable=False, comment='Number of losing trades'),
    sa.Column('win_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Win rate percentage'),
    sa.Column('sharpe_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='Sharpe ratio'),
    sa.Column('sortino_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='Sortino ratio'),
    sa.Column('max_drawdown', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='Maximum drawdown'),
    sa.Column('max_drawdown_percent', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Max drawdown %'),
    sa.Column('profit_factor', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='Profit factor'),
    sa.Column('avg_win', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Average winning trade'),
    sa.Column('avg_loss', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Average losing trade'),
    sa.Column('total_return', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='Total return'),
    sa.Column('total_return_percent', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Total return %'),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Equity curve time series'),
    sa.Column('trade_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Trade log details'),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active)'),
    sa.CheckConstraint("timeframe IN ('1m', '5m', '15m', '1h', '4h', '1d')", name='ck_backtests_timeframe'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Backtest results and performance metrics'
    )
    op.create_index('idx_backtests_bot_created', 'backtests', ['bot_id', 'created_at'], unique=False)
    op.create_index('idx_backtests_deleted_at', 'backtests', ['deleted_at'], unique=False)
    op.create_index('idx_backtests_strategy_created', 'backtests', ['strategy_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_backtests_deleted_at'), 'backtests', ['deleted_at'], unique=False)
    op.create_table('bot_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment ID'),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Performance date'),
    sa.Column('trades_count', sa.Integer(), nullable=False, comment='Number of trades'),
    sa.Column('winning_trades', sa.Integer(), nullable=False, comment='Winning trades'),
    sa.Column('losing_trades', sa.Integer(), nullable=False, comment='Losing trades'),
    sa.Column('daily_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Daily P&L'),
    sa.Column('cumulative_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Cumulative P&L'),
    sa.Column('win_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Daily win rate %'),
    sa.Column('sharpe_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='Daily Sharpe ratio'),
    sa.Column('max_drawdown', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='Current max drawdown'),
    sa.Column('volatility', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='Daily volatility'),
    sa.Column('volume_traded', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Volume traded'),
    sa.Column('fees_paid', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Fees paid'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Bot daily performance metrics (partitioned by date quarterly)'
    )
    op.create_index('idx_bot_performance_bot_date', 'bot_performance', ['bot_id', 'date'], unique=True)
    op.create_table('positions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=True, comment='Bot managing this position'),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading symbol'),
    sa.Column('side', sa.String(length=10), nullable=False, comment='LONG or SHORT'),
    sa.Column('entry_price', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Average entry price'),
    sa.Column('mark_price', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Current mark price'),
    sa.Column('liquidation_price', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Liquidation price'),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Position size'),
    sa.Column('pnl', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Total P&L'),
    sa.Column('pnl_percent', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='P&L percentage'),
    sa.Column('unrealized_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Unrealized P&L'),
    sa.Column('realized_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Realized P&L'),
    sa.Column('stop_loss', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Stop loss price'),
    sa.Column('take_profit', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Take profit price'),
    sa.Column('leverage', sa.Integer(), nullable=False, comment='Position leverage'),
    sa.Column('margin_mode', sa.String(length=10), nullable=False, comment='Margin mode'),
    sa.Column('margin_used', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Margin required'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Position status'),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False, comment='Position opened timestamp'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='Position closed timestamp'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active)'),
    sa.CheckConstraint("margin_mode IN ('ISOLATED', 'CROSS')", name='ck_positions_margin_mode'),
    sa.CheckConstraint("side IN ('LONG', 'SHORT')", name='ck_positions_side'),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED', 'LIQUIDATED')", name='ck_positions_status'),
    sa.CheckConstraint('leverage >= 1 AND leverage <= 125', name='ck_positions_leverage'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Trading positions (partitioned by opened_at quarterly)'
    )
    op.create_index('idx_positions_bot_opened', 'positions', ['bot_id', 'opened_at'], unique=False)
    op.create_index('idx_positions_deleted_at', 'positions', ['deleted_at'], unique=False)
    op.create_index('idx_positions_user_symbol_status', 'positions', ['user_id', 'symbol', 'exchange_id', 'status'], unique=False)
    op.create_index(op.f('ix_positions_deleted_at'), 'positions', ['deleted_at'], unique=False)
    op.create_table('risk_limits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=True, comment='Bot-specific limits (NULL = account level)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Risk limit name'),
    sa.Column('max_position_size', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Max position size (base asset)'),
    sa.Column('max_position_value', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Max position value (quote asset)'),
    sa.Column('max_open_positions', sa.Integer(), nullable=True, comment='Max concurrent positions'),
    sa.Column('max_leverage', sa.Integer(), nullable=True, comment='Maximum allowed leverage'),
    sa.Column('max_daily_loss', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Max daily loss (quote asset)'),
    sa.Column('max_drawdown_percent', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Max drawdown %'),
    sa.Column('stop_trading_on_limit', sa.String(length=20), nullable=False, comment='Action: PAUSE, CLOSE_ALL'),
    sa.Column('risk_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Custom risk rules (JSON)'),
    sa.Column('is_active', sa.String(length=20), nullable=False, comment='Limit active status'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active)'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Risk management limits and rules'
    )
    op.create_index('idx_risk_limits_deleted_at', 'risk_limits', ['deleted_at'], unique=False)
    op.create_index('idx_risk_limits_user_bot', 'risk_limits', ['user_id', 'bot_id'], unique=False)
    op.create_index(op.f('ix_risk_limits_deleted_at'), 'risk_limits', ['deleted_at'], unique=False)
    op.create_table('orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True, comment='Associated position ID'),
    sa.Column('bot_id', sa.UUID(), nullable=True, comment='Bot that created this order'),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading symbol (BTCUSDT)'),
    sa.Column('side', sa.String(length=10), nullable=False, comment='LONG or SHORT'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='Order type'),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Order quantity'),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Limit price (NULL for MARKET)'),
    sa.Column('stop_price', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Stop trigger price'),
    sa.Column('callback_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Trailing stop callback rate (%)'),
    sa.Column('leverage', sa.Integer(), nullable=False, comment='Leverage (1-125)'),
    sa.Column('margin_mode', sa.String(length=10), nullable=False, comment='ISOLATED or CROSS'),
    sa.Column('position_mode', sa.String(length=10), nullable=False, comment='ONE_WAY or HEDGE'),
    sa.Column('time_in_force', sa.String(length=10), nullable=False, comment='Time in force'),
    sa.Column('stop_loss', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Stop loss price'),
    sa.Column('take_profit', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Take profit price'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Order status'),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True, comment='Exchange order ID'),
    sa.Column('filled_quantity', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Filled quantity'),
    sa.Column('filled_avg_price', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='Average fill price'),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional order metadata'),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True, comment='Order filled timestamp'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='Order cancelled timestamp'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = active)'),
    sa.CheckConstraint("margin_mode IN ('ISOLATED', 'CROSS')", name='ck_orders_margin_mode'),
    sa.CheckConstraint("order_type IN ('MARKET', 'LIMIT', 'STOP_MARKET', 'STOP_LIMIT', 'TRAILING_STOP')", name='ck_orders_type'),
    sa.CheckConstraint("position_mode IN ('ONE_WAY', 'HEDGE')", name='ck_orders_position_mode'),
    sa.CheckConstraint("side IN ('LONG', 'SHORT')", name='ck_orders_side'),
    sa.CheckConstraint("status IN ('PENDING', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED')", name='ck_orders_status'),
    sa.CheckConstraint("time_in_force IN ('GTC', 'IOC', 'FOK', 'GTX')", name='ck_orders_tif'),
    sa.CheckConstraint('leverage >= 1 AND leverage <= 125', name='ck_orders_leverage'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_order_id'),
    comment='Trading orders (partitioned by created_at monthly)'
    )
    op.create_index('idx_orders_bot_id', 'orders', ['bot_id'], unique=False)
    op.create_index('idx_orders_deleted_at', 'orders', ['deleted_at'], unique=False)
    op.create_index('idx_orders_exchange_order_id', 'orders', ['exchange_order_id'], unique=True)
    op.create_index('idx_orders_position_id', 'orders', ['position_id'], unique=False)
    op.create_index('idx_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('idx_orders_user_symbol_exchange', 'orders', ['user_id', 'symbol', 'exchange_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_deleted_at'), 'orders', ['deleted_at'], unique=False)
    op.create_table('trades',
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading symbol'),
    sa.Column('side', sa.String(length=10), nullable=False, comment='BUY or SELL'),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Execution price'),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Executed quantity'),
    sa.Column('fee', sa.DECIMAL(precision=20, scale=8), nullable=False, comment='Trading fee'),
    sa.Column('fee_currency', sa.String(length=10), nullable=True, comment='Fee currency'),
    sa.Column('pnl', sa.DECIMAL(precision=20, scale=8), nullable=True, comment='P&L for this trade'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Trade status'),
    sa.Column('exchange_trade_id', sa.String(length=100), nullable=True, comment='Exchange trade ID'),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional trade metadata'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False, comment='Trade execution timestamp'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v7 primary key'),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='ck_trades_side'),
    sa.CheckConstraint("status IN ('SUCCESS', 'FAILED')", name='ck_trades_status'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_trade_id'),
    comment='Trade executions (immutable, partitioned by executed_at monthly)'
    )
    op.create_index('idx_trades_exchange_trade_id', 'trades', ['exchange_trade_id'], unique=True)
    op.create_index('idx_trades_order_id', 'trades', ['order_id'], unique=False)
    op.create_index('idx_trades_position_executed', 'trades', ['position_id', 'executed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_position_executed', table_name='trades')
    op.drop_index('idx_trades_order_id', table_name='trades')
    op.drop_index('idx_trades_exchange_trade_id', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_orders_deleted_at'), table_name='orders')
    op.drop_index('idx_orders_user_symbol_exchange', table_name='orders')
    op.drop_index('idx_orders_status_created', table_name='orders')
    op.drop_index('idx_orders_position_id', table_name='orders')
    op.drop_index('idx_orders_exchange_order_id', table_name='orders')
    op.drop_index('idx_orders_deleted_at', table_name='orders')
    op.drop_index('idx_orders_bot_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_risk_limits_deleted_at'), table_name='risk_limits')
    op.drop_index('idx_risk_limits_user_bot', table_name='risk_limits')
    op.drop_index('idx_risk_limits_deleted_at', table_name='risk_limits')
    op.drop_table('risk_limits')
    op.drop_index(op.f('ix_positions_deleted_at'), table_name='positions')
    op.drop_index('idx_positions_user_symbol_status', table_name='positions')
    op.drop_index('idx_positions_deleted_at', table_name='positions')
    op.drop_index('idx_positions_bot_opened', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_bot_performance_bot_date', table_name='bot_performance')
    op.drop_table('bot_performance')
    op.drop_index(op.f('ix_backtests_deleted_at'), table_name='backtests')
    op.drop_index('idx_backtests_strategy_created', table_name='backtests')
    op.drop_index('idx_backtests_deleted_at', table_name='backtests')
    op.drop_index('idx_backtests_bot_created', table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_bots_deleted_at'), table_name='bots')
    op.drop_index('idx_bots_user_status', table_name='bots')
    op.drop_index('idx_bots_strategy_id', table_name='bots')
    op.drop_index('idx_bots_last_run_at', table_name='bots')
    op.drop_index('idx_bots_deleted_at', table_name='bots')
    op.drop_table('bots')
    op.drop_index('idx_symbols_symbol', table_name='symbols')
    op.drop_index('idx_symbols_exchange_status', table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_strategies_deleted_at'), table_name='strategies')
    op.drop_index('idx_strategies_user_type', table_name='strategies')
    op.drop_index('idx_strategies_is_public', table_name='strategies')
    op.drop_index('idx_strategies_deleted_at', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('idx_orderbook_symbol_time', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index('idx_market_prices_symbol_interval_time', table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_database_configs_deleted_at'), table_name='database_configs')
    op.drop_index('idx_database_configs_user_id', table_name='database_configs')
    op.drop_index('idx_database_configs_deleted_at', table_name='database_configs')
    op.drop_table('database_configs')
    op.drop_index(op.f('ix_api_connections_deleted_at'), table_name='api_connections')
    op.drop_index('idx_api_connections_user_exchange', table_name='api_connections')
    op.drop_index('idx_api_connections_deleted_at', table_name='api_connections')
    op.drop_table('api_connections')
    op.drop_index('idx_alerts_user_symbol_status', table_name='alerts')
    op.drop_index('idx_alerts_status_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_deleted_at', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_exchanges_code', table_name='exchanges')
    op.drop_table('exchanges')
    op.drop_index('idx_event_queue_status_created', table_name='event_queue')
    op.drop_index('idx_event_queue_expires_at', table_name='event_queue')
    op.drop_index('idx_event_queue_event_id', table_name='event_queue')
    op.drop_table('event_queue')
    # ### end Alembic commands ###
